steps:
# --- ÉTAPE 1: Build du Frontend ---
- name: 'node:20'
  entrypoint: 'npm'
  args: ['install']
- name: 'node:20'
  entrypoint: 'npm'
  args: ['run', 'build']

# --- ÉTAPE 2: Déployer sur Firebase Hosting ---
# Le compte de service a maintenant les permissions, donc une commande simple suffit.
- name: 'node:20'
  entrypoint: 'npx'
  args: ['-p', 'firebase-tools', 'firebase', 'deploy', '--only', 'hosting:eventflow-ifc', '--project', '${PROJECT_ID}']

# --- ÉTAPES BACKEND (toujours désactivées pour le moment) ---
# ...

options:
  logging: CLOUD_LOGGING_ONLY
